version: '3'

services:
  backend-server:
    build:
      context: server
      dockerfile: docker/dev.dockerfile
    ports:
      - 9998:9998
    volumes:
      - "./server:/root"
      - "${GENEY_DATA_PATH}:/root/data"
    environment:
      - GENEY_DATA_PATH=/root/data
      - GENEY_URL=localhost
  
  redis:
    image: "redis:alpine"