version: '3'

services:
  ui-server:
    image: pjtatlow/geney-ui:0.0.1
    ports:
      - "10000:10000"
  backend-server:
    image: pjtatlow/geney-server:0.0.2
    ports:
      - "9998:9998"
    volumes:
      - "./data:/root/data"
    environment:
      - GUNICORN_CMD_ARGS=--workers=4 --bind=:9998 --worker-class=eventlet --worker-connections 100
      - GENEY_DATA_PATH=/root/data